-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU8Q/cr4LBgXzr4KEQfpB9wfzeX4BjhjZJjNF3457jTqgCgYIKoZIzj0DAQehRANCAAS2fCIa5iKA151gFVK18pWcDbLm7iyvxJmafheONXqTSkySYCdKaHYyoRLNgqBOu2OcGB/P4vPcVWZiQDDlRBdZ
-----END PRIVATE KEY-----